-- MySQL Script generated by MySQL Workbench
-- Mon Oct 27 10:56:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `join_datetime` DATETIME NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `address` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `plot` TEXT NULL,
  `publisher` VARCHAR(45) NULL,
  `genre` VARCHAR(45) NULL,
  `translator` VARCHAR(45) NULL,
  `price` INT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`book_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL,
  `create_datetime` DATETIME NULL,
  `publisher` VARCHAR(45) NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_datetime` DATETIME NULL,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_user1_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`delivery` (
  `delivery_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NULL,
  `delivery_company` VARCHAR(45) NULL,
  `tracking_id` VARCHAR(45) NULL,
  `status` ENUM("결제완료", "상품준비중", "배송준비중", "배송중", "배송완료") NULL,
  `order_order_id` INT NOT NULL,
  PRIMARY KEY (`delivery_id`),
  INDEX `fk_delivery_order1_idx` (`order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_delivery_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `mydb`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart` (
  `cart_id` INT NOT NULL AUTO_INCREMENT,
  `user_user_id` INT NOT NULL,
  PRIMARY KEY (`cart_id`),
  INDEX `fk_cart_user_idx` (`user_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_user`
    FOREIGN KEY (`user_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`book_has_author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`book_has_author` (
  `book_book_id` INT NOT NULL,
  `author_author_id` INT NOT NULL,
  PRIMARY KEY (`book_book_id`, `author_author_id`),
  INDEX `fk_book_has_author_author1_idx` (`author_author_id` ASC) VISIBLE,
  INDEX `fk_book_has_author_book1_idx` (`book_book_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_has_author_book1`
    FOREIGN KEY (`book_book_id`)
    REFERENCES `mydb`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_has_author_author1`
    FOREIGN KEY (`author_author_id`)
    REFERENCES `mydb`.`author` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_has_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_has_book` (
  `order_order_id` INT NOT NULL,
  `book_book_id` INT NOT NULL,
  PRIMARY KEY (`order_order_id`, `book_book_id`),
  INDEX `fk_order_has_book_book1_idx` (`book_book_id` ASC) VISIBLE,
  INDEX `fk_order_has_book_order1_idx` (`order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_has_book_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `mydb`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_has_book_book1`
    FOREIGN KEY (`book_book_id`)
    REFERENCES `mydb`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cart_has_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cart_has_book` (
  `cart_cart_id` INT NOT NULL,
  `book_book_id` INT NOT NULL,
  PRIMARY KEY (`cart_cart_id`, `book_book_id`),
  INDEX `fk_cart_has_book_book1_idx` (`book_book_id` ASC) VISIBLE,
  INDEX `fk_cart_has_book_cart1_idx` (`cart_cart_id` ASC) VISIBLE,
  CONSTRAINT `fk_cart_has_book_cart1`
    FOREIGN KEY (`cart_cart_id`)
    REFERENCES `mydb`.`cart` (`cart_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_has_book_book1`
    FOREIGN KEY (`book_book_id`)
    REFERENCES `mydb`.`book` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
